project_id = "ewsiwbxjjhjqhbgemkxo"

[functions.ai-chat]
verify_jwt = false

[functions.ai-summary]
verify_jwt = false

[functions.ai-notes]
verify_jwt = false

[functions.ai-qa-suggestions]
verify_jwt = false
[functions.test-function]
enabled = true
verify_jwt = true
import_map = "./functions/test-function/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-function/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-function/*.html" ]
